config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses do
    get '/enroll/', to: 'courses#enroll', as: 'enroll'
  end
  get '/categories/:id', to: 'categories#show', as: 'categories'
  get '/learning/', to: 'learning#index', as: 'learning'
  get '/manage/', to: 'manage#index', as: 'manage'
  root 'courses#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_many :course_categories
  has_many :courses, through: :course_categories
  validates :name, presence: true, length: { minimum: 3 }
end

app/models/course.rb
class Course < ApplicationRecord
  # validations
  validates :title, presence: true, length: { minimum: 3, maximum: 32 }
  validates :description, presence: true, length: { maximum: 256 }

  # many to many - courses <=> categories
  has_many :course_categories
  has_many :categories, through: :course_categories
  # one to many - user (author) <=> courses
  belongs_to :author, class_name: "User", foreign_key: :author_id
  # many to many - users (learners) <=> courses
  has_many :enrolled_courses
  has_many :users, through: :enrolled_courses

  # attached recording
  has_one_attached :recording
end

app/models/course_category.rb
class CourseCategory < ApplicationRecord
  belongs_to :category
  belongs_to :course
end

app/models/enrolled_course.rb
class EnrolledCourse < ApplicationRecord
  validates :course_id, uniqueness: { scope: [:user_id] }
  validate :user_not_enroll_own_course

  belongs_to :user
  belongs_to :course

  def user_not_enroll_own_course
    if Course.find(course_id).author_id == user_id
      errors.add(:user_id, "can't enroll self course")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # one to many - user (author) <=> courses
  has_many :created_courses, class_name: "Course", foreign_key: :author_id, dependent: :destroy
  # many to many - users (learners) <=> courses
  has_many :enrolled_courses
  has_many :courses, through: :enrolled_courses

  # devise configuration
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # https://github.com/heartcombo/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  validate :validate_username

  attr_writer :login

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      conditions[:email].downcase! if conditions[:email]
      where(conditions.to_h).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_query

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def after_sign_in_path_for(user)
    courses_path
  end

  private

  def set_query
    @q = Course.ransack(params[:q])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category

  def show
    @courses = @q.result(distinct: true) & @category.courses
    @categories = Category.all
    @should_render_categories = true
  end

  private

  def set_category
    @category = Category.friendly.find(params[:id])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!, only: %i[ show new create edit update destroy enroll ]
  before_action :set_course, only: %i[ show preview edit update destroy ]
  before_action :only_course_author, only: %i[ edit destroy ]

  def index
    @courses = @q.result(distinct: true) || Course.all()
    @categories = Category.all()
    @should_render_categories = true
  end

  def new
    @course = Course.new()
    @categories = Category.all()
  end

  def create
    @categories = Category.all()
    @course = current_user.created_courses.create(course_params)
    if @course.save
      flash[:success] = "Course added successfully."
      redirect_to courses_path
    else
      flash.now[:danger] = "Error. Course not added."
      render :new
    end
  end

  def show
    if current_user.created_courses.exclude?(@course) && current_user.courses.exclude?(@course)
      render :preview
    end
  end

  def preview
  end

  def edit
    @categories = Category.all()
  end

  def update
    if @course.update(course_params)
      flash[:success] = "Course updated successfully."
      redirect_to(@course)
    else
      flash.now[:danger] = "Error. Course not updated."
      render :edit
    end
  end

  def destroy
    @course.destroy
    flash[:success] = "Course deleted successfully."
    redirect_to courses_path, status: :see_other
  end

  def enroll
    course = Course.find_by(id: params[:course_id])
    enrolledCourse = current_user.enrolled_courses.build(course_id: course.id)
    if enrolledCourse.valid? && enrolledCourse.save
      flash[:success] = "Enrolled successfully."
      redirect_to course
    else
      flash[:danger] = "You can not enroll your own course. You can enroll course only once."
      redirect_to courses_path
    end
  end

  private
  def only_course_author
    if current_user.created_courses.exclude?(@course)
      flash[:warning] = "You are not allowed to edit/delete this course."
      redirect_to courses_path
    end
  end

  def course_params
    params.require(:course).permit(:title, :recording, :description, :is_free, category_ids: [])
  end

  def set_course
    @course = Course.find_by(id: params[:id])
  end
end

app/controllers/learning_controller.rb
class LearningController < ApplicationController
  before_action :authenticate_user!

  def index
    @courses = current_user.courses
  end

end

app/controllers/manage_controller.rb
class ManageController < ApplicationController
  before_action :authenticate_user!

  def index
    @courses = current_user.created_courses
  end
end

app/controllers/turbo_controller.rb
class TurboController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
  end
end

app/views/categories/show.html.erb
<div class="container pt-4">
  <h2 class="diplay-6 text-center mb-4">
    All <b><%= @category.name.downcase %></b> courses
    <small class="text-muted d-block">Find the best one for yourself</small>
  </h2>
  <% if @courses.empty? %>
    <h5 class="text-center my-5">No courses yet... Feel free to add one!</h5>
  <% end %>
  <div class="row row-cols-1 row-cols-md-2 row-cols-xxl-3 g-4 mb-4">
    <% @courses.each do |c| %>
      <div class="col">
        <%= render partial: "shared/card", locals: { course: c } %>
      </div>
    <% end %>
  </div>
</div>

app/views/courses/_form.html.erb
<%= javascript_import_module_tag("utils") %>
<%= form_with(model: @course, class: "form-floating my-4") do |form| %>
  <div class="form-floating mb-3 col-xl-8">
    <%= form.text_field :title, class: "form-control", placeholder: "Enter the course title", required: true %>
    <%= form.label :title, class: "form-label" %>
  </div>
  <div class="mb-3">
    <%= form.label "Pick categories", class: "form-label" %>
    <%= form.select :category_ids, @categories.collect{|c| [ c.name, c.id ]} , {}, { class: "form-control js-multiple-select", multiple: true } %>
  </div>
  <div class="mb-3">
    <%= form.label "Upload course recording", class: "form-label" if !@course.new_record? %>
    <%= form.file_field :recording, accept: "video/mp4,video/x-m4v,video/*", class: "form-control d-block", style: "width: unset;", required: true, disabled: !@course.new_record? %>
  </div>
  <div class="form-floating mb-3">
    <%= form.text_area :description, class: "form-control", placeholder: "Enter the course description", required: true %>
    <%= form.label :description, class: "form-label" %>
  </div>
  <div class="form-check mb-3">
    <%= form.check_box :is_free, { class: "form-check-input" }, "true", "false" %>
    <%= form.label "Share for free", class: "form-check-label" %>
  </div>
  <% if defined?(actions) %>
    <div class="form-actions d-sm-flex justify-content-sm-center justify-content-md-start d-grid gap-1">
      <%= form.submit @course.new_record? ? "Post a new course" : "Update course", class: "btn btn-primary" %>
      <%= link_to "Back to course list", courses_path, class: "btn btn-secondary" if actions.include?(:back) %>
      <%= link_to "Delete article", @course, class: "btn btn-danger", data: { turbo_method: :delete } if actions.include?(:delete) %>
    </div>
  <% end %>
<% end %>

app/views/courses/edit.html.erb
<div class="container pt-4">
  <h2 class="diplay-6 text-center">Edit a course</h2>
  <%= render partial: "courses/form", locals: { actions: %i[ back delete ] } %>
</div>

app/views/courses/index.html.erb
<div class="container pt-4">
  <h2 class="diplay-6 text-center mb-4">
    All kNOW courses
    <small class="text-muted d-block">Find the best one for yourself</small>
  </h2>
  <% if @q.result(distinct: true).empty? %>
    <h5 class="text-center text-muted my-5">Apologizes, I did not find any course you are looking for</h5>
  <% elsif @courses.empty? %>
    <h5 class="text-center my-5">No courses yet... Feel free to add one!</h5>
  <% end %>
  <div class="row row-cols-1 row-cols-md-2 row-cols-xxl-3 g-4 mb-4">
    <% @courses.each do |c| %>
      <div class="col">
        <%= render partial: "shared/card", locals: { course: c } %>
      </div>
    <% end %>
  </div>
</div>

app/views/courses/new.html.erb
<div class="container pt-4">
  <h2 class="diplay-6 text-center">Adding new course</h2>
  <%= render partial: "courses/form", locals: { actions: %i[ back ] } %>
</div>

app/views/courses/preview.html.erb
<div class="container py-5">
  <div class="d-flex justify-content-center align-items-baseline mb-3">
    <h4 class="d-inline-block lead me-1">Preview of: </h4>
    <h3 class="d-inline-block ms-1"><%= @course.title %></h3>
  </div>
  <% if @course.recording.attached? %>
    <div class="ratio ratio-16x9 preview-photo">
      <h5 class="preview-info">That's video thumbnail - to watch course enroll it <%= link_to "here", course_enroll_path(@course) %></h5>
      <%= image_tag url_for(@course.recording.preview(resize_to_limit: [854, 480]).processed), alt:"Course thumbnail" %>
    </div>
  <% end %>
  <div class="row my-4 pt-2 bg-light">
    <div class="col-10 mx-auto">
      <h5 class="text-center">
        Author notes:
      </h5>
    </div>
    <div class="col-8 mx-auto">
      <p class="m-0 text-center" style="word-wrap: anywhere;">
        <%= @course.description %>
      </p>
    </div>
  </div>
  <div class="d-grid gap-2 col-10 col-md-6 col-lg-4 mx-auto pt-4">
    <%= link_to "Back to course list", courses_path, class: "btn btn-primary" %>
  </div>
  <figcaption class="text-center text-muted my-4 pt-2">
    Created and published by <%= @course.author.username %>
  </figcaption>
</div>

app/views/courses/show.html.erb
<div class="container py-5">
  <div class="d-flex justify-content-center align-items-baseline mb-3">
    <h4 class="d-inline-block lead me-1">Learning now: </h4>
    <h3 class="d-inline-block ms-1"><%= @course.title %></h3>
  </div>
  <% if @course.recording.attached? %>
    <div class="ratio ratio-16x9">
      <%= video_tag url_for(@course.recording), controls: true, autobuffer: true %>
    </div>
  <% end %>
  <div class="row my-4 pt-2 bg-light">
    <div class="col-10 mx-auto">
      <h5 class="text-center">
        Author notes:
      </h5>
    </div>
    <div class="col-8 mx-auto">
      <p class="m-0 text-center" style="word-wrap: anywhere;">
        <%= @course.description %>
      </p>
    </div>
  </div>
  <div class="d-grid gap-2 col-10 col-md-6 col-lg-4 mx-auto pt-4">
    <%= link_to "Back to course list", courses_path, class: "btn btn-primary" %>
  </div>
  <figcaption class="text-center text-muted my-4 pt-2">
    Created and published by <%= @course.author.username %>
  </figcaption>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>kNOW</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag "/apple-touch-icon.png", rel: "apple-touch-icon" %>
    <%= favicon_link_tag "/favicon-32x32.png", sizes: "32x32", rel: "icon" %>
    <%= favicon_link_tag "/favicon-16x16.png", sizes:"16x16", rel: "icon" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-light">
    <%= render partial: "shared/navbar" %>
    <%= render partial: "shared/bar" if @should_render_categories %>
    <main>
      <%= yield %>
    </main>
    <%= render partial: "shared/flash" %>
  </body>
</html>

app/views/learning/_horizontal_card.html.erb
<div class="card mb-3">
  <div class="row g-0">
    <div class="col-lg-6 col-xl-4">
      <%= image_tag url_for(course.recording.preview(resize_to_limit:  [854, 480]).processed), class:"rounded-start card-photo", alt:"Course thumbnail" %>
    </div>
    <div class="col-lg-6 col-xl-8">
      <div class="card-body d-flex flex-column h-100">
        <h5 class="card-title"><%= course.title %></h5>
        <p class="card-text"><%= truncate(course.description, length: 50) %></p>
        <p class="card-text"><small class="text-muted">Shared by <%= course.author.username %></small></p>
        <div class="card-actions d-grid gap-2 d-md-block mt-auto">
          <%= link_to "Continue learning", course, class: "btn btn-primary active flex-grow-1", data: { turbo: false } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/learning/index.html.erb
<div class="container pt-4">
  <h2 class="diplay-6 text-center mb-4">
    Your learning list
  </h2>
  <% if @courses.empty? %>
    <h5 class="text-center my-5">You have not joined any course yet, choose one <%= link_to "here", courses_path %></h5>
  <% end %>
  <div class="container-fluid">
    <% @courses.each do |c| %>
      <%= render partial: "shared/horizontal_card", locals: { course: c, actions: %i[ learn ] } %>
    <% end %>
  </div>
</div>

app/views/shared/_bar.html.erb
<nav class="container-fluid bg-light">
  <ul class="list-group list-group-horizontal overflow-auto hide-scrollbar mx-xl-5">
    <li class="list-group-item horizontal-scroll-item flex-shrink-0 bg-light">
      <%= link_to "All courses", root_path, class: class_names("btn",
        "btn-primary": @category.nil?, "btn-secondary": !@category.nil?) %>
    </li>
      <div class="category-divider"></div>
    <% @categories.each do |category| %>
      <li class="list-group-item horizontal-scroll-item flex-shrink-0 bg-light">
        <%= link_to category.name, categories_path(category), class: class_names("btn",
            "btn-primary": @category == category, "btn-secondary": @category != category) %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/shared/_card.html.erb
<%= link_to course, { class: "clickable-card", data: { turbo: false } } do %>
  <div class="card">
    <%= image_tag url_for(course.recording.preview(resize_to_limit:  [854, 480]).processed), class:"img-fluid rounded-top card-photo", alt:"Course thumbnail" %>
    <div class="card-body d-flex flex-column h-100">
      <h5 class="card-title d-flex">
        <%= course.title %>
        <div class="flex-grow-1"></div>
        <span class="<%= class_names("badge", "bg-secondary": course.is_free, "bg-dark": !course.is_free) %>">
          <%= course.is_free ? "Free" : "Paid" %>
        </span>
      </h5>
      <div class="card-categories mb-2">
        <% course.categories.each do |category| %>
          <span class="badge rounded-pill text-bg-light">
            <%= category.name %>
          </span>
        <% end %>
      </div>
      <p class="card-text mb-1"><%= truncate(course.description, length: 256) %></p>
      <div class="card-actions d-flex gap-1 justify-content-end ms-auto w-50 mt-3">
        <% if user_signed_in? && current_user.courses.include?(course) %>
          <%= link_to "Continue learning", course, class: "btn btn-sm btn-primary flex-grow-1" %>
        <% elsif user_signed_in? && current_user.created_courses.include?(course) %>
          <%= link_to "Edit", edit_course_path(course), class: "btn btn-sm btn-outline-secondary flex-grow-1", data: { turbo: false } %>
          <%= link_to "Delete", course, class: "btn btn-sm btn-outline-danger flex-grow-1", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        <% else %>
          <%= link_to "Enroll", course_enroll_path(course), class: "btn btn-sm btn-primary flex-grow-1" %>
          <%= link_to "Preview", course, class: "btn btn-sm btn-secondary flex-grow-1", data: { turbo: false } %>
        <% end %>
      </div>
    </div>
    <div class="card-footer">
      <p class="blockquote-footer m-0">
        Shared & created by <%= course.author.username %>
      </p>
    </div>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="<%= "position-fixed m-2 sticky-bottom bottom-0 end-0 alert alert-#{name} alert-dismissible fade show" %>" style="z-index: 1200;" role="alert" >
    <strong>
      <%= msg %>
    </strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_horizontal_card.html.erb
<div class="card mb-3">
  <div class="row g-0">
    <div class="col-lg-6 col-xl-4">
      <%= image_tag url_for(course.recording.preview(resize_to_limit:  [854, 480]).processed), class:"rounded-start card-photo", alt:"Course thumbnail" %>
    </div>
    <div class="col-lg-6 col-xl-8">
      <div class="card-body d-flex flex-column h-100">
        <h5 class="card-title"><%= course.title %></h5>
        <div class="card-categories mb-2">
          <% course.categories.each do |category| %>
            <span class="badge rounded-pill text-bg-light">
              <%= category.name %>
            </span>
          <% end %>
        </div>
        <p class="card-text"><%= truncate(course.description, length: 256) %></p>
        <p class="card-text"><small class="text-muted">Shared by <%= course.author.username %></small></p>
        <div class="card-actions d-grid gap-2 d-md-block mt-auto">
          <%= link_to "Continue learning", course, class: "btn btn-primary active flex-grow-1", data: { turbo: false } if actions.include?(:learn) %>
          <%= link_to "Edit", edit_course_path(course), class: "btn btn-secondary active flex-grow-1", data: { turbo: false } if actions.include?(:edit) %>
          <%= link_to "Delete", course, class: "btn btn-danger active flex-grow-1", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } if actions.include?(:delete) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-lg">
    <% if user_signed_in? %>
      <div class="navbar-nav">
        <li class="d-lg-none dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
              <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
              <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
            </svg>
            Your account
          </a>
          <ul class="dropdown-menu">
            <h6 class="dropdown-header">Signed as <%= current_user.username %></h6>
            <%= link_to "Edit account", edit_user_registration_path, class:"dropdown-item" %>
            <hr class="dropdown-divider">
            <%= link_to "My courses", manage_path, class:"dropdown-item" %>
            <hr class="dropdown-divider">
            <%= link_to "Sign out", destroy_user_session_path, class: "dropdown-item" %>
          </ul>
        </li>
      </div>
    <% else %>
      <%= link_to "Sign in", new_user_session_path, class: "d-lg-none ms-2 btn btn-primary" %>
    <% end %>
    <%= link_to root_path, class: "navbar-brand d-flex" do %>
      <%= image_tag "wide_logo.png", alt: "kNOW logo", class:"brand-logo-image" %>
    <% end %>
    <button class="btn border border-0 navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#000" class="bi bi-list" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
      </svg>
    </button>
    <div class="collapse navbar-collapse" id="navbarContent">
      <ul class="navbar-nav me-auto my-1">
        <% if user_signed_in? %>
          <%= link_to "Create course", new_course_path, class: "nav-link active mx-1", data: {turbo: false} %>
          <%= link_to "Learn", learning_path, class: "nav-link active mx-1" %>
          <div class="navbar-divider collapse navbar-collapse me-2"></div>
          <div class="collapse navbar-collapse">
            <li class="dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                </svg>
                Your account
              </a>
              <ul class="dropdown-menu">
                <h6 class="dropdown-header">Signed as <%= current_user.username %></h6>
                <%= link_to "Edit account", edit_user_registration_path, class:"dropdown-item" %>
                <hr class="dropdown-divider">
                <%= link_to "My courses", manage_path, class:"dropdown-item" %>
                <hr class="dropdown-divider">
                <%= link_to "Sign out", destroy_user_session_path, class: "dropdown-item" %>
              </ul>
            </li>
          </div>
        <% end %>
      </ul>
      <%= search_form_for(@q, class: "d-flex", role: "search") do |f| %>
        <%= f.search_field :title_or_description_cont_any, class: "form-control me-1", type:"search", placeholder:"Search for course...", aria_label: "Search"  %>
        <%= f.button nil, class: "btn btn-primary d-flex justify-content-center align-items-center" do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search mx-1" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
          </svg>
        <% end %>
      <% end %>
      <% if !user_signed_in? %>
        <div class="collapse navbar-collapse flex-grow-0">
          <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary ms-2" %>
        </div>
      <% end %>
    </div>
  </div>
</nav>